/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.routenplaner.gui.components;

import de.abring.routenplaner.gui.Route;
import de.abring.routenplaner.gui.Route3;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Karima
 */
public class JPanelTour extends javax.swing.JPanel {

    private final Route3 route;
    /**
     * Creates new form JPanelTour
     * @param route
     */
    public JPanelTour(Route3 route) {
        this.route = route;
        initComponents();
        updateTexte();
    }
    
    public final void updateTexte() {
        this.jTxtName.setText(this.route.getRouteName());
        this.jTxtDriver.setText(this.route.getDriver());
        this.jTxtCoDriver.setText(this.route.getCoDriver());
        this.jTxtCar.setText(this.route.getCar());
        this.jBtnColor.setBackground(this.route.getColor());
        this.jChkMapMarkerVisible.setSelected(this.route.isMarkerVisible());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblDriver = new javax.swing.JLabel();
        jLblCoDriver = new javax.swing.JLabel();
        jLblCar = new javax.swing.JLabel();
        jLblColor = new javax.swing.JLabel();
        jTxtDriver = new javax.swing.JTextField();
        jTxtCoDriver = new javax.swing.JTextField();
        jTxtCar = new javax.swing.JTextField();
        jBtnColor = new javax.swing.JButton();
        jLblName = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jChkMapMarkerVisible = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(214, 223, 247));
        setMaximumSize(new java.awt.Dimension(400, 127));
        setMinimumSize(new java.awt.Dimension(200, 127));
        setPreferredSize(new java.awt.Dimension(250, 127));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblDriver.setLabelFor(jTxtDriver);
        jLblDriver.setText("Fahrer");

        jLblCoDriver.setLabelFor(jTxtCoDriver);
        jLblCoDriver.setText("Beifahrer");

        jLblCar.setLabelFor(jTxtCar);
        jLblCar.setText("Fahrzeug");

        jLblColor.setLabelFor(jBtnColor);
        jLblColor.setText("Farbe");

        jTxtDriver.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtDriverFocusLost(evt);
            }
        });
        jTxtDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDriverActionPerformed(evt);
            }
        });

        jTxtCoDriver.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCoDriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCoDriverFocusLost(evt);
            }
        });
        jTxtCoDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCoDriverActionPerformed(evt);
            }
        });

        jTxtCar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCarFocusLost(evt);
            }
        });
        jTxtCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCarActionPerformed(evt);
            }
        });

        jBtnColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBtnColor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnColor.setIconTextGap(1);
        jBtnColor.setMaximumSize(new java.awt.Dimension(73, 20));
        jBtnColor.setMinimumSize(new java.awt.Dimension(73, 20));
        jBtnColor.setPreferredSize(new java.awt.Dimension(33, 20));
        jBtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnColorActionPerformed(evt);
            }
        });

        jLblName.setLabelFor(jTxtName);
        jLblName.setText("Name");

        jTxtName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNameFocusLost(evt);
            }
        });
        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jChkMapMarkerVisible.setSelected(true);
        jChkMapMarkerVisible.setText("anzeigen");
        jChkMapMarkerVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMapMarkerVisibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDriver)
                            .addComponent(jLblName)
                            .addComponent(jLblCoDriver))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDriver)
                            .addComponent(jTxtName)
                            .addComponent(jTxtCoDriver)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCar)
                            .addComponent(jLblColor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jChkMapMarkerVisible, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(jTxtCar))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblName)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDriver)
                    .addComponent(jTxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCoDriver)
                    .addComponent(jTxtCoDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkMapMarkerVisible))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDriverActionPerformed
        this.route.setDriver(jTxtDriver.getText());
    }//GEN-LAST:event_jTxtDriverActionPerformed

    private void jTxtCoDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCoDriverActionPerformed
        this.route.setCoDriver(jTxtCoDriver.getText());
    }//GEN-LAST:event_jTxtCoDriverActionPerformed

    private void jTxtCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCarActionPerformed
        this.route.setCar(jTxtCar.getText());
    }//GEN-LAST:event_jTxtCarActionPerformed

    private void jBtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Tour-Farbe", this.route.getColor());
        this.jBtnColor.setBackground(color);
        this.route.setTourColor(color);
    }//GEN-LAST:event_jBtnColorActionPerformed

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        this.route.setRouteName(jTxtName.getText());
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jChkMapMarkerVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMapMarkerVisibleActionPerformed
        this.route.setMapMarkerVisible(this.jChkMapMarkerVisible.isSelected());
    }//GEN-LAST:event_jChkMapMarkerVisibleActionPerformed

    private void jTxtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNameFocusLost
        this.route.setRouteName(jTxtName.getText());
    }//GEN-LAST:event_jTxtNameFocusLost

    private void jTxtDriverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDriverFocusLost
        this.route.setDriver(jTxtDriver.getText());
    }//GEN-LAST:event_jTxtDriverFocusLost

    private void jTxtCoDriverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCoDriverFocusLost
        this.route.setCoDriver(jTxtCoDriver.getText());
    }//GEN-LAST:event_jTxtCoDriverFocusLost

    private void jTxtCarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCarFocusLost
        this.route.setDriver(jTxtDriver.getText());
    }//GEN-LAST:event_jTxtCarFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnColor;
    private javax.swing.JCheckBox jChkMapMarkerVisible;
    private javax.swing.JLabel jLblCar;
    private javax.swing.JLabel jLblCoDriver;
    private javax.swing.JLabel jLblColor;
    private javax.swing.JLabel jLblDriver;
    private javax.swing.JLabel jLblName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCar;
    private javax.swing.JTextField jTxtCoDriver;
    private javax.swing.JTextField jTxtDriver;
    private javax.swing.JTextField jTxtName;
    // End of variables declaration//GEN-END:variables
}
