/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.helfer.gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Karima
 */
public class JTextFieldGoogle extends javax.swing.JPanel {

    /**
     * Creates new form JTextFieldGoogle
     */
    public JTextFieldGoogle() {
        initComponents();
    }

    
    public void setText(Object value) {
        if (value instanceof String) {
            jText.setText((String) value);
        }
    }
    
    public Object getText() {
        return jText.getText();
    }
    
    @Override
    public String toString() {
        return jText.getText();
    }
    public void searchGoogle() {
        String googleString = "http://www.google.com/search?q=";
        if(Desktop.isDesktopSupported()){
            try {
                String urlString = URLEncoder.encode(this.jText.getText(), "UTF-8");
                urlString = urlString.replace("+++%2B-+", "");
                urlString = urlString.replace("%2B-+", "");
                urlString += "&ie=UTF-8";
                Logger.getLogger(JTextFieldGoogle.class.getName()).log(Level.FINE, "{0}{1}", new Object[]{googleString, urlString});
                URL url = new URL(googleString + urlString); //Some instantiated URL object
                URI uri = url.toURI();
            Desktop desktop = Desktop.getDesktop();
                desktop.browse(uri);
            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(JTextFieldGoogle.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Runtime runtime = Runtime.getRuntime();
            String urlString = this.jText.getText();
            urlString = urlString.replace("+++%2B-+", "");
            urlString = urlString.replace("%2B-+", "");
            try {
                Logger.getLogger(JTextFieldGoogle.class.getName()).log(Level.FINE, "{0}{1}", new Object[]{googleString, urlString});
                runtime.exec("xdg-open " + googleString + urlString);
            } catch (IOException e) {
                Logger.getLogger(JTextFieldGoogle.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();
        jText = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(32767, 22));
        setMinimumSize(new java.awt.Dimension(50, 22));
        setPreferredSize(new java.awt.Dimension(394, 22));

        jButton.setText("Google");
        jButton.setMaximumSize(new java.awt.Dimension(65, 22));
        jButton.setMinimumSize(new java.awt.Dimension(65, 22));
        jButton.setPreferredSize(new java.awt.Dimension(65, 22));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jText, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jText))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        searchGoogle();
    }//GEN-LAST:event_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton;
    public javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
}
