/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.routenplaner.gui.dialogues;

import de.abring.routenplaner.jxtreetableroute.JXNoRootTreeTableModelAddress;
import de.abring.routenplaner.jxtreetableroute.entries.JXTreeRouteEntry;
import java.util.List;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Bring
 */
public class Table extends javax.swing.JDialog {

    public static int DIALOG_ABORT      = -1;
    
    
    private boolean OKActionPerformed;
    
    /**
     * Creates new Form Table
     * @param parent
     * @param modal
     */
    public Table(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.OKActionPerformed = false;
        pack();
        this.jXTreeTableRoute.updateUI();
    }
    
    /**
     * Creates new FavDialogForm Table
     * @param parent
     * @param modal
     * @param title
     * @param liste
     * @return 
     */
    public static int JXTreeTableAddressFavDialog(java.awt.Frame parent, boolean modal, String title, List<JXTreeRouteEntry> liste) {
        Table favDialog = new Table(parent, modal);
        favDialog.setTitle(title);
        favDialog.getjXTreeTableRoute().setJxTreeRouteEntryList(liste);
        favDialog.getjXTreeTableRoute().setDragEnabled(false);
        favDialog.getjXTreeTableRoute().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int[] columns = {
            JXNoRootTreeTableModelAddress.EMPTY,
            JXNoRootTreeTableModelAddress.NAME
        };
        favDialog.getjXTreeTableRoute().handleColumns(columns);
        favDialog.getjXTreeTableRoute().updateUI();
        favDialog.setVisible(true);
        
        if (!favDialog.isOKActionPerformed())
            return Table.DIALOG_ABORT;
        return favDialog.getjXTreeTableRoute().getSelectedRow();
    }
    public static int JXTreeTableAddressClientDialog(java.awt.Frame parent, boolean modal, String title, List<JXTreeRouteEntry> liste) {
        Table favDialog = new Table(parent, modal);
        favDialog.setTitle(title);
        favDialog.getjXTreeTableRoute().setJxTreeRouteEntryList(liste);
        favDialog.getjXTreeTableRoute().setDragEnabled(false);
        favDialog.getjXTreeTableRoute().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int[] columns = {
            JXNoRootTreeTableModelAddress.EMPTY,
            JXNoRootTreeTableModelAddress.ID,
            JXNoRootTreeTableModelAddress.NAME,
            JXNoRootTreeTableModelAddress.TIME,
            JXNoRootTreeTableModelAddress.DURATION,
            JXNoRootTreeTableModelAddress.APPOINTMENT,
            JXNoRootTreeTableModelAddress.ITEMS,
            JXNoRootTreeTableModelAddress.ADDRESS_ROUTE,
            JXNoRootTreeTableModelAddress.FAVORIT,
        };
        favDialog.getjXTreeTableRoute().handleColumns(columns);
        favDialog.getjXTreeTableRoute().updateUI();
        favDialog.setVisible(true);
        
        if (!favDialog.isOKActionPerformed())
            return Table.DIALOG_ABORT;
        return favDialog.getjXTreeTableRoute().getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jBtnOK = new javax.swing.JButton();
        jBtnAbort = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jXTreeTableRoute = new de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnOK.setText("OK");
        jBtnOK.setEnabled(false);
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        jBtnAbort.setText("Abbrechne");
        jBtnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAbortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jBtnAbort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnOK)
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOK)
                    .addComponent(jBtnAbort))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTreeTableRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTreeTableRouteMouseClicked(evt);
            }
        });
        jXTreeTableRoute.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jXTreeTableRouteValueChanged(evt);
            }
        });
        jXTreeTableRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXTreeTableRouteActionPerformed(evt);
            }
        });
        jScrollPane.setViewportView(jXTreeTableRoute);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        this.OKActionPerformed = true;
        this.setVisible(false);
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAbortActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnAbortActionPerformed

    private void jXTreeTableRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXTreeTableRouteActionPerformed
        jBtnOK.setEnabled(true);
    }//GEN-LAST:event_jXTreeTableRouteActionPerformed

    private void jXTreeTableRouteValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jXTreeTableRouteValueChanged
        jBtnOK.setEnabled(true);
    }//GEN-LAST:event_jXTreeTableRouteValueChanged

    private void jXTreeTableRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTreeTableRouteMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            if (jBtnOK.isEnabled()) {
                this.OKActionPerformed = true;
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jXTreeTableRouteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbort;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute jXTreeTableRoute;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the OKActionPerformed
     */
    public boolean isOKActionPerformed() {
        return OKActionPerformed;
    }

    /**
     * @return the jXTreeTableRoute
     */
    public de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute getjXTreeTableRoute() {
        return jXTreeTableRoute;
    }

    /**
     * @return the jBtnAbort
     */
    public javax.swing.JButton getjBtnAbort() {
        return jBtnAbort;
    }

    /**
     * @return the jBtnOK
     */
    public javax.swing.JButton getjBtnOK() {
        return jBtnOK;
    }
}
