/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.routenplaner;

import de.abring.helfer.primitives.*;
import de.abring.routenplaner.jxtreetableroute.*;
import de.abring.routenplaner.jxtreetableroute.entries.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.event.TableModelEvent;
import de.abring.helfer.maproute.LookupAddress;
import de.abring.helfer.maproute.MapAddress;

/**
 *
 * @author Karima
 */
public class jxTreeTableTest extends javax.swing.JFrame {

    protected List<JXTreeRouteEntry> entryList1;
    
    private float oldDividerLocationPercent;
    
    /**
     * Creates new form jxTreeTableTest
     */
    public jxTreeTableTest() {
        initComponents();
        oldDividerLocationPercent = (float) this.jSplitPane1.getDividerLocation() / (float) this.jSplitPane1.getWidth();
        initOtherComponents();
    }

    private void initOtherComponents() {
        this.entryList1 = new ArrayList<>();
        
        addTestItems();
                
        jXTreeTableRoute1.setJxTreeRouteEntryList(entryList1);
        jXTreeTableRoute1.getModel().addTableModelListener((TableModelEvent evt) -> {
//            refreshTable(jXTreeTableRoute1);
            jXTreeTableRoute1.updateUI();
        });
        
        int[] columns = {
            JXNoRootTreeTableModelAddress.EMPTY,
            JXNoRootTreeTableModelAddress.NAME,
            JXNoRootTreeTableModelAddress.ADDRESS,
        };
        jXTreeTableRoute2.handleColumns(columns);
        jXTreeTableRoute2.getModel().addTableModelListener((TableModelEvent evt) -> {
//            refreshTable(jXTreeTableRoute2);
            jXTreeTableRoute2.updateUI();
        });
    }
    
    
    private void addTestItems() {
        entryList1.add(new JXTreeRouteStart(new TimeOfDay("09:00")));
        
        JXTreeRouteTour tour = new JXTreeRouteTour("Herzogenrath", "AB", "CL", "AC-LC 110", "Info");
        tour.setColor(Color.MAGENTA);
        entryList1.add(tour);
        
        JXTreeRouteAddressFav fav = new JXTreeRouteAddressFav(new MapAddress("Voccartstraße 66, 52136 Herzogenrath"));
        fav.setDuration(new TimeOfDay("00:20"));
        fav.setName("Media Markt Herzogenrath");
        fav.setAppointment(new Appointment(new TimeOfDay("10:00"),new TimeOfDay("20:00")));
        entryList1.add(fav);
        
        JXTreeRouteAddressClient cli = new JXTreeRouteAddressClient(new MapAddress("Am Dorfend 12, 46509 Xanten"), fav);
        cli.setDuration(new TimeOfDay("00:25"));
        cli.setAppointment(new Appointment(new TimeOfDay("09:00"),new TimeOfDay("15:00")));
        cli.setName("Ilona Bring");
        
        entryList1.add(cli);
        entryList1.add(new JXTreeRouteEnd());
        
        jXTreeTableRoute2.addItem(new JXTreeRouteStart(new TimeOfDay("09:00")));
        
        LookupAddress address;
        address = new LookupAddress(this, true, "Voccartstraße 66, 52136 Herzogenrath");
        address.setVisible(true);
        JXTreeRouteAddressFav fav2 = new JXTreeRouteAddressFav(address.getMapAddress());
        fav2.setDuration(new TimeOfDay("00:20"));
        fav2.setName("Media Markt Herzogenrath");
        fav2.setAppointment(new Appointment(new TimeOfDay("10:00"),new TimeOfDay("20:00")));
        jXTreeTableRoute2.addItem(fav2);
        
        JXTreeRouteAddressFav fav3 = new JXTreeRouteAddressFav(new MapAddress("Schloss-Schönau-Straße 6-8, 52072 Aachen"));
        fav3.setDuration(new TimeOfDay("00:30"));
        fav3.setName("Löschmann & Claßen GbR");
        fav3.setAppointment(new Appointment(new TimeOfDay("09:00"),new TimeOfDay("18:00")));
        jXTreeTableRoute2.addItem(fav3);
        
        JXTreeRouteAddressClient cli2 = new JXTreeRouteAddressClient(new MapAddress("Kastanienweg 9, 52074 Aachen"), fav);
        cli2.setDuration(new TimeOfDay("00:45"));
        cli2.setAppointment(new Appointment(new TimeOfDay("09:00"),new TimeOfDay("15:00")));
        cli2.setName("Andreas Bring");
        
        jXTreeTableRoute2.addItem(cli2);
        jXTreeTableRoute2.addItem(new JXTreeRouteEnd());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTableRoute1 = new de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTreeTableRoute2 = new de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane1ComponentResized(evt);
            }
        });
        jSplitPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSplitPane1PropertyChange(evt);
            }
        });

        jXTreeTableRoute1.setShowGrid(false);
        jScrollPane1.setViewportView(jXTreeTableRoute1);
        jXTreeTableRoute1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setViewportView(jXTreeTableRoute2);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSplitPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane1ComponentResized
        this.jSplitPane1.setDividerLocation(Math.round(evt.getComponent().getWidth() * oldDividerLocationPercent));
    }//GEN-LAST:event_jSplitPane1ComponentResized

    private void jSplitPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSplitPane1PropertyChange
        if (evt.getPropertyName().equals("dividerLocation")) {
            oldDividerLocationPercent = (float) ((int) evt.getNewValue()) / (float) this.jSplitPane1.getWidth();
            System.out.println(oldDividerLocationPercent);
        }
    }//GEN-LAST:event_jSplitPane1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jxTreeTableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jxTreeTableTest().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute jXTreeTableRoute1;
    private de.abring.routenplaner.jxtreetableroute.JXTreeTableRoute jXTreeTableRoute2;
    // End of variables declaration//GEN-END:variables
}
