/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.pdferkennung.gui.dialogues;

import de.abring.pdferkennung.gui.JPictureFrame;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.ImageType;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author Karima
 */
public class showPDFPage extends javax.swing.JDialog {

    private final PDFRenderer renderer;
    BufferedImage image = null;

    /**
     * Creates new form showPDFPage
     * @param parent
     * @param modal
     * @param doc
     * @param page
     */
    public showPDFPage(java.awt.Frame parent, boolean modal, PDDocument doc, int page) {
        super(parent, modal);
        initComponents();
        this.renderer = new PDFRenderer(doc);
        try {
            this.image = renderer.renderImageWithDPI(page, 120, ImageType.RGB);
        } catch (IOException ex) {
            Logger.getLogger(JPictureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (this.image == null) {
            this.jLabel.setSize(this.jScrollPane.getSize());
            this.jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/abring/pdferkennung/image/red-x.png")));
        } else {
            this.jLabel.setSize(new Dimension(this.image.getWidth(), this.image.getHeight()));
            this.jLabel.setIcon(new ImageIcon(this.image));
        }
    }
    
    public showPDFPage(java.awt.Frame parent, boolean modal, BufferedImage image, float scaleFactor) {
        super(parent, modal);
        initComponents();
        this.renderer = null;
        //this.image = scale(image, 1024, Math.round(1024.0f * image.getHeight()) / image.getWidth());
        this.image = scale(image, Math.round((float) image.getWidth() * scaleFactor), Math.round((float) image.getHeight() * scaleFactor));
        if (this.image == null) {
            this.jLabel.setSize(this.jScrollPane.getSize());
            this.jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/abring/pdferkennung/image/red-x.png")));
        } else {
            this.jLabel.setSize(new Dimension(this.image.getWidth(), this.image.getHeight()));
            this.jLabel.setIcon(new ImageIcon(this.image));
        }
    }

    public static BufferedImage scale(BufferedImage src, int w, int h) {
        BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        int x, y;
        int ww = src.getWidth();
        int hh = src.getHeight();
        int[] ys = new int[h];
        for (y = 0; y < h; y++)
            ys[y] = y * hh / h;
        for (x = 0; x < w; x++) {
            int newX = x * ww / w;
            for (y = 0; y < h; y++) {
                int col = src.getRGB(newX, ys[y]);
                img.setRGB(x, y, col);
            }
        }
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/abring/pdferkennung/image/red-x.png"))); // NOI18N
        jScrollPane.setViewportView(jLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
